
run-daemon:
	export PYRO_HMAC_KEY='2d736347ff7487d559d7fb3cfc1e92dd'
	../python predictor-daemon.py

run-pyro-nameserver:
	export PYRO_HMAC_KEY='2d736347ff7487d559d7fb3cfc1e92dd'
	../python -Wignore -m Pyro4.naming